## Standard imports

In [1]:
import math

import numpy as np

import scipy as sp

import matplotlib.pyplot as plt

%matplotlib inline

import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)
warnings.filterwarnings("ignore", category=UserWarning)

import sympy as sym
import sympy.plotting.plot as symplot

from IPython.display import display, Math
sym.init_printing()

## Matrix-matrix multiplication

In [6]:
def print_shape(A, B):
    print(f"{A.shape} @ {B.shape}")

In [7]:
M = 3
N = 4
K = 6

A = np.random.randint(-10, 10, (M,N))
B = np.random.randint(-10, 10, (N,K))

print(f"{A.shape} @ {B.shape}")
display(A@B)

print(f"{B.T.shape} @ {A.T.shape}")
display(B.T@A.T)

(3, 4) @ (4, 6)


array([[  69,   67,  178,  -58,   72,   25],
       [-155, -138,  -25,  191,  -19,  -74],
       [-134,  -99,  -24,  162,   -6,  -51]])

(6, 4) @ (4, 3)


array([[  69, -155, -134],
       [  67, -138,  -99],
       [ 178,  -25,  -24],
       [ -58,  191,  162],
       [  72,  -19,   -6],
       [  25,  -74,  -51]])

In [8]:
v = np.random.randint(-10, 10, (5,1))
w = np.random.randint(-10, 10, (5,1))
display(v)
display(w)

print_shape(v, w.T)
v @ w.T

print_shape(v.T, w)
v.T @ w

array([[ 6],
       [-1],
       [-6],
       [ 7],
       [-7]])

array([[ 2],
       [ 7],
       [-1],
       [-3],
       [ 4]])

(5, 1) @ (1, 5)
(1, 5) @ (5, 1)


array([[-38]])

### Matrix-matrix multiplication and transpose - the reverse order

In [5]:
# Define the shape of the arrays (3x3 matrix)
n = (3, 3)

# Generate 4 arrays (L, I, V, E) filled with random standard normal values
L = np.random.standard_normal(n)
I = np.random.standard_normal(n)
V = np.random.standard_normal(n)
E = np.random.standard_normal(n)

# Calculate 'res1' by multiplying arrays L, I, V, and E, and then transpose the result
res1 = np.matrix.transpose(L @ I @ V @ E)

# Calculate 'res2' by transposing arrays E, V, I, and L separately, and then multiply them in reverse order
res2 = np.matrix.transpose(E) @ np.matrix.transpose(V) @ np.matrix.transpose(I) @ np.matrix.transpose(L)

# Calculate the difference between 'res1' and 'res2'
difference = res1 - res2

# Display the difference matrix
print("Difference matrix:")
print(difference)

# Note: The difference matrix is expected to be a zero matrix, but due to floating-point imprecisions,
# there might be very small non-zero values. These differences are typically negligible and arise from
# the way computers represent real numbers in binary format.


Difference matrix:
[[ 0.00000000e+00  8.88178420e-16  8.88178420e-16]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-7.10542736e-15  6.66133815e-16  1.77635684e-15]]


## Matrix-vector multiplication

In [6]:
# Define the size of the square matrix (4x4)
m = 4

# Generate a random matrix N filled with integers rounded to the nearest whole number
N = np.round(10 * np.random.standard_normal((m, m)))

# Calculate the symmetric matrix S by multiplying the transpose of N with N, then scaling by m^2
S = np.round(np.matrix.transpose(N) @ N / m**2)

# Generate a random column vector of size 4, where each element is in the range of -10 to 10 (inclusive)
w = np.random.randint(-10, 11, size=(4, 1))

# Perform matrix-vector multiplication using the generated matrix and array
# The result 'result_Nw' will be a column vector with 4 elements
result_Nw = N @ w

# Perform matrix-vector multiplication using the symmetric matrix and transposed array (column vector)
# The result 'result_Sw' will be a column vector with 4 elements
result_Sw = S @ w

# Perform vector-matrix multiplication using the transposed column vector and matrix
# The result 'result_wN' will be a row vector with 4 elements
result_wN = np.transpose(w) @ N

# Perform left vector-matrix multiplication using the transposed column vector and symmetric matrix
# The result 'result_wS' will be a row vector with 4 elements
result_wS = np.transpose(w) @ S

# Display the original matrix N, the symmetric matrix S, the vector w, and the results of the matrix-vector and left matrix-vector multiplications
print("Original Matrix N:")
print(N)

print("\nSymmetric Matrix S:")
print(S)

print("\nVector w:")
print(w)

print("\nResult of Matrix-Vector Multiplication (N @ w):")
print(result_Nw)

print("\nResult of Matrix-Vector Multiplication (S @ w):")
print(result_Sw)

print("\nResult of Left Matrix-Vector Multiplication (w^T @ N):")
print(result_wN)

print("\nResult of Left Matrix-Vector Multiplication (w^T @ S):")
print(result_wS)


Original Matrix N:
[[ -1.  -9.  -7.  12.]
 [ -5.  16.   5. -10.]
 [  4.  -8.  -2.  10.]
 [  7.  15.  -5. -18.]]

Symmetric Matrix S:
[[  6.   0.  -4.  -3.]
 [  0.  39.   5. -39.]
 [ -4.   5.   6.  -4.]
 [ -3. -39.  -4.  42.]]

Vector w:
[[-9]
 [-2]
 [-7]
 [10]]

Result of Matrix-Vector Multiplication (N @ w):
[[ 196.]
 [-122.]
 [  94.]
 [-238.]]

Result of Matrix-Vector Multiplication (S @ w):
[[ -56.]
 [-503.]
 [ -56.]
 [ 553.]]

Result of Left Matrix-Vector Multiplication (w^T @ N):
[[  61.  255.   17. -338.]]

Result of Left Matrix-Vector Multiplication (w^T @ S):
[[ -56. -503.  -56.  553.]]


# Lore ipsum

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut consectetur massa. Etiam malesuada ac libero et rhoncus. Pellentesque vel nulla sit amet turpis vehicula efficitur. Vivamus cursus elit quam, sollicitudin venenatis lectus porta in. Praesent tempus nunc in mi sollicitudin volutpat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas lacus diam, ultrices at mauris eu, blandit maximus mauris. Quisque sagittis, lorem quis ornare scelerisque, turpis sem gravida purus, ut aliquet sapien mi eget felis. Ut tristique tempor bibendum. In nec arcu sed leo commodo imperdiet. Nam ac lacus elit. Vivamus efficitur urna nec dolor aliquet bibendum. Nunc scelerisque, justo ac suscipit vestibulum, lacus urna pharetra elit, vitae semper ipsum lacus quis neque. Nulla nec sem dapibus, egestas lorem eget, ultrices augue. Proin ullamcorper velit enim, vitae laoreet orci tristique sit amet. Donec sit amet odio orci.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut consectetur massa. Etiam malesuada ac libero et rhoncus. Pellentesque vel nulla sit amet turpis vehicula efficitur. Vivamus cursus elit quam, sollicitudin venenatis lectus porta in. Praesent tempus nunc in mi sollicitudin volutpat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas lacus diam, ultrices at mauris eu, blandit maximus mauris. Quisque sagittis, lorem quis ornare scelerisque, turpis sem gravida purus, ut aliquet sapien mi eget felis. Ut tristique tempor bibendum. In nec arcu sed leo commodo imperdiet. Nam ac lacus elit. Vivamus efficitur urna nec dolor aliquet bibendum. Nunc scelerisque, justo ac suscipit vestibulum, lacus urna pharetra elit, vitae semper ipsum lacus quis neque. Nulla nec sem dapibus, egestas lorem eget, ultrices augue. Proin ullamcorper velit enim, vitae laoreet orci tristique sit amet. Donec sit amet odio orci.