## Standard imports

In [2]:
import math

import numpy as np
import pandas as pd
from numpy.random import randn
import numpy.random as rnd

import scipy as sp
from scipy import stats
from scipy import special

import matplotlib as mpl
import matplotlib.pyplot as plt

%matplotlib inline

import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)
warnings.filterwarnings("ignore", category=UserWarning)

import seaborn as sns
from bokeh.plotting import figure, show

import sympy as sym
import sympy.plotting.plot as symplot

from IPython.display import display, Math
sym.init_printing()

x,y,z = sym.symbols('x,y,z')
a,b,c,d,e,f,g,h = sym.symbols('a,b,c,d,e,f,g,h')

## Matrix diversity

In [5]:
# square vs. rectangular
S = np.random.randn(5,5)
R = np.random.randn(5,2) # 5 rows, 2 columns
print(S)
print(R)

# identity
I = np.eye(3)
print(I)

# zeros
Z = np.zeros((4,4))
print(Z)

[[ 1.31355262 -0.54788428 -0.09767523  0.73555204 -0.51571875]
 [-0.29502533  1.13936973  0.85999915 -0.15552766  0.54876919]
 [ 0.00391652  0.01249723  1.55341126  1.13597538  0.28626526]
 [-0.59981773 -0.88327077 -1.19900967  0.39027341 -0.90348494]
 [-0.23978361  2.25909683  0.83430017  0.82299847  0.20270903]]
[[ 1.93342091 -0.1192125 ]
 [-2.88341397 -0.30489568]
 [-0.05115854  0.11590687]
 [ 0.13728353 -0.99023239]
 [ 0.50182596 -0.60788311]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
# diagonal
D = np.diag([ 1, 2, 3, 5, 2 ])
print(D)

# create triangular matrix from full matrices
S = np.random.randn(5,5)
# upper triangular matrix
U = np.triu(S)
# lower triangular matrix
L = np.tril(S)
print(U)
print(L)

# concatenate matrices; sizes must match
A = np.random.randn(4,3)
B = np.random.randn(4,5)
C = np.concatenate((A,B),axis=1)
print(C)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 5 0]
 [0 0 0 0 2]]
[[-0.38206973  0.39908626 -0.16721567  0.01423022  0.0318426 ]
 [ 0.         -0.7757176   1.1774668  -1.03271133 -0.18614417]
 [ 0.          0.          0.42043529 -1.63866457 -1.3911023 ]
 [ 0.          0.          0.          0.5254112   0.66289253]
 [ 0.          0.          0.          0.          0.12873232]]
[[-0.38206973  0.          0.          0.          0.        ]
 [ 1.12606707 -0.7757176   0.          0.          0.        ]
 [-0.27919804 -0.82821993  0.42043529  0.          0.        ]
 [ 0.17585292  0.20059663  0.94861636  0.5254112   0.        ]
 [ 0.2507893   0.05446062  1.27126512  1.88811166  0.12873232]]
[[ 0.56662759 -0.63600519  0.99523539 -0.46691806 -0.27632629 -0.59891067
  -0.72504868 -0.17164295]
 [ 0.2513978  -0.83620794  0.71060146  1.34124994  1.92049823  0.73781175
  -1.68036182 -0.82738918]
 [ 1.4597569  -0.61945464  0.29468678  0.22024953  0.27344311  0.28424556
   0.12751512  0.0437376 ]

## Matrix addition and subtraction

In [27]:
# create random matrices
A = np.random.randn(5,4)
B = np.random.randn(5,3)
C = np.random.randn(5,4)

# try to add matrices with different sizes
try:
    A+B
except Exception as e:
    print(e, "\n")

# "shifting" a matrix
l = .3 # lambda
n = 5  # size of square matrix
D = np.random.randint(-10, 10, (n, n)) # can only shift a square matrix
Ds = D + l*np.eye(N)

print(Ds)

operands could not be broadcast together with shapes (5,4) (5,3)  

[[-1.7 -5.  -4.  -9.   3. ]
 [ 1.  -8.7  7.   9.   2. ]
 [-2.  -2.   1.3  0.   4. ]
 [ 5.   4.  -9.  -3.7  8. ]
 [ 0.   4.   3.  -1.  -4.7]]


## Matrix-scalar multiplication

In [28]:
# define matrix and scalar
M = np.array([ [1, 2], [2, 5] ])
s = 2

# pre- and post-multiplication is the same:
print( M*s )
print( s*M )

[[ 2  4]
 [ 4 10]]
[[ 2  4]
 [ 4 10]]


## Transpose

In [39]:
M = np.array([ [1,2,3],
               [4,5,6] ])

print(M, '\n')
print(M.T, '\n') # one transpose
print(M.T.T, '\n') # double-transpose returns the original matrix

# can also use the function transpose
print(np.transpose(M), '\n')
print(np.transpose(np.transpose(M)))

[[1 2 3]
 [4 5 6]] 

[[1 4]
 [2 5]
 [3 6]] 

[[1 2 3]
 [4 5 6]] 

[[1 4]
 [2 5]
 [3 6]] 

[[1 2 3]
 [4 5 6]]


### Hermitian transpose

In [50]:
# warning! be careful when using complex matrices
C = np.array([ 
    [1+1j, 2, 3-4j],
    [4-1j, 5+22j, 6]
             ])

print(C), print('')
print(C.T), print('')
print(np.transpose(C)), print('')

# Note: In MATLAB, the transpose is the Hermitian transpose; 
#       in Python, you need to call the Hermitian explicitly 
#       by first converting from an array into a matrix
print("note the sign flips!")
print(np.matrix(C).H)

[[1. +1.j 2. +0.j 3. -4.j]
 [4. -1.j 5.+22.j 6. +0.j]]

[[1. +1.j 4. -1.j]
 [2. +0.j 5.+22.j]
 [3. -4.j 6. +0.j]]

[[1. +1.j 4. -1.j]
 [2. +0.j 5.+22.j]
 [3. -4.j 6. +0.j]]

note the sign flips!
[[1. -1.j 4. +1.j]
 [2. -0.j 5.-22.j]
 [3. +4.j 6. -0.j]]


# Lore ipsum

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut consectetur massa. Etiam malesuada ac libero et rhoncus. Pellentesque vel nulla sit amet turpis vehicula efficitur. Vivamus cursus elit quam, sollicitudin venenatis lectus porta in. Praesent tempus nunc in mi sollicitudin volutpat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas lacus diam, ultrices at mauris eu, blandit maximus mauris. Quisque sagittis, lorem quis ornare scelerisque, turpis sem gravida purus, ut aliquet sapien mi eget felis. Ut tristique tempor bibendum. In nec arcu sed leo commodo imperdiet. Nam ac lacus elit. Vivamus efficitur urna nec dolor aliquet bibendum. Nunc scelerisque, justo ac suscipit vestibulum, lacus urna pharetra elit, vitae semper ipsum lacus quis neque. Nulla nec sem dapibus, egestas lorem eget, ultrices augue. Proin ullamcorper velit enim, vitae laoreet orci tristique sit amet. Donec sit amet odio orci.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut consectetur massa. Etiam malesuada ac libero et rhoncus. Pellentesque vel nulla sit amet turpis vehicula efficitur. Vivamus cursus elit quam, sollicitudin venenatis lectus porta in. Praesent tempus nunc in mi sollicitudin volutpat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas lacus diam, ultrices at mauris eu, blandit maximus mauris. Quisque sagittis, lorem quis ornare scelerisque, turpis sem gravida purus, ut aliquet sapien mi eget felis. Ut tristique tempor bibendum. In nec arcu sed leo commodo imperdiet. Nam ac lacus elit. Vivamus efficitur urna nec dolor aliquet bibendum. Nunc scelerisque, justo ac suscipit vestibulum, lacus urna pharetra elit, vitae semper ipsum lacus quis neque. Nulla nec sem dapibus, egestas lorem eget, ultrices augue. Proin ullamcorper velit enim, vitae laoreet orci tristique sit amet. Donec sit amet odio orci.