## Standard imports

In [3]:
import math

import numpy as np
import pandas as pd
from numpy.random import randn
import numpy.random as rnd

import scipy as sp
from scipy import stats
from scipy import special

import matplotlib as mpl
import matplotlib.pyplot as plt

%matplotlib inline

import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)
warnings.filterwarnings("ignore", category=UserWarning)

import seaborn as sns
from bokeh.plotting import figure, show

import sympy as sym
import sympy.plotting.plot as symplot

from IPython.display import display, Math
sym.init_printing()

x,y,z = sym.symbols('x,y,z')
a,b,c,d,e,f,g,h = sym.symbols('a,b,c,d,e,f,g,h')

## Title_00

In [6]:
def print_shape(A, B):
    print(f"{A.shape} @ {B.shape}")

In [7]:
M = 3
N = 4
K = 6

A = np.random.randint(-10, 10, (M,N))
B = np.random.randint(-10, 10, (N,K))

print(f"{A.shape} @ {B.shape}")
display(A@B)

print(f"{B.T.shape} @ {A.T.shape}")
display(B.T@A.T)

(3, 4) @ (4, 6)


array([[  69,   67,  178,  -58,   72,   25],
       [-155, -138,  -25,  191,  -19,  -74],
       [-134,  -99,  -24,  162,   -6,  -51]])

(6, 4) @ (4, 3)


array([[  69, -155, -134],
       [  67, -138,  -99],
       [ 178,  -25,  -24],
       [ -58,  191,  162],
       [  72,  -19,   -6],
       [  25,  -74,  -51]])

In [8]:
v = np.random.randint(-10, 10, (5,1))
w = np.random.randint(-10, 10, (5,1))
display(v)
display(w)

print_shape(v, w.T)
v @ w.T

print_shape(v.T, w)
v.T @ w

array([[ 6],
       [-1],
       [-6],
       [ 7],
       [-7]])

array([[ 2],
       [ 7],
       [-1],
       [-3],
       [ 4]])

(5, 1) @ (1, 5)
(1, 5) @ (5, 1)


array([[-38]])

# Lore ipsum

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut consectetur massa. Etiam malesuada ac libero et rhoncus. Pellentesque vel nulla sit amet turpis vehicula efficitur. Vivamus cursus elit quam, sollicitudin venenatis lectus porta in. Praesent tempus nunc in mi sollicitudin volutpat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas lacus diam, ultrices at mauris eu, blandit maximus mauris. Quisque sagittis, lorem quis ornare scelerisque, turpis sem gravida purus, ut aliquet sapien mi eget felis. Ut tristique tempor bibendum. In nec arcu sed leo commodo imperdiet. Nam ac lacus elit. Vivamus efficitur urna nec dolor aliquet bibendum. Nunc scelerisque, justo ac suscipit vestibulum, lacus urna pharetra elit, vitae semper ipsum lacus quis neque. Nulla nec sem dapibus, egestas lorem eget, ultrices augue. Proin ullamcorper velit enim, vitae laoreet orci tristique sit amet. Donec sit amet odio orci.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut consectetur massa. Etiam malesuada ac libero et rhoncus. Pellentesque vel nulla sit amet turpis vehicula efficitur. Vivamus cursus elit quam, sollicitudin venenatis lectus porta in. Praesent tempus nunc in mi sollicitudin volutpat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas lacus diam, ultrices at mauris eu, blandit maximus mauris. Quisque sagittis, lorem quis ornare scelerisque, turpis sem gravida purus, ut aliquet sapien mi eget felis. Ut tristique tempor bibendum. In nec arcu sed leo commodo imperdiet. Nam ac lacus elit. Vivamus efficitur urna nec dolor aliquet bibendum. Nunc scelerisque, justo ac suscipit vestibulum, lacus urna pharetra elit, vitae semper ipsum lacus quis neque. Nulla nec sem dapibus, egestas lorem eget, ultrices augue. Proin ullamcorper velit enim, vitae laoreet orci tristique sit amet. Donec sit amet odio orci.